### ISSUE TITLE
'Python3' isnt recgonized as a cmdlet.

### ISSUE THREAD

**Issue by SpaceDevz** [gotr00t0day/Gsec#1]
Hey! I know its in beta and I was just testing it.

I tried to do a search on my website, and after it got all the ports and stuff it ended up with this result:

![image](https://user-images.githubusercontent.com/24994624/184519514-d1671003-5b00-4a6a-a377-50f0bed51ba1.png)

Maybe you should do:

`python || python3` just so both cmds work.

**Comment by SpaceDevz** [comment]
Also:

![image](https://user-images.githubusercontent.com/24994624/184519558-45205f88-6801-4b48-840c-c2d339a1b13b.png)

**Comment by gotr00t0day** [comment]
> Also:
> 
> ![image](https://user-images.githubusercontent.com/24994624/184519558-45205f88-6801-4b48-840c-c2d339a1b13b.png)

Thanks for catching this, I actually forgot to push the change to github when I changed to function name lol.

**Comment by gotr00t0day** [comment]
> Hey! I know its in beta and I was just testing it.
> 
> I tried to do a search on my website, and after it got all the ports and stuff it ended up with this result:
> 
> ![image](https://user-images.githubusercontent.com/24994624/184519514-d1671003-5b00-4a6a-a377-50f0bed51ba1.png)
> 
> Maybe you should do:
> 
> `python || python3` just so both cmds work.

This might be on your end, is python3 in your path?
