### ISSUE TITLE
[FTL] Could not run nuclei: no templates provided for scan

### ISSUE THREAD

**Issue by ricamz** [gotr00t0day/Gsec#10]
Hi.

I placed nuclei-templates directory inside where I run the scan, in the / directory (through link), in the home directory (through link) but still having this error.

[FTL] Could not run nuclei: no templates provided for scan

How can I solve this issue?

Gsec version 1.5.

Regards

RS

**Comment by ricamz** [comment]
This issue is solved. Just copied the nuclei-templates to the home diretory.

But now it says scan finished, but no results, even to a knowingly bad web page - http://itsecgames.com/

The command I used:

python3 gsec.py -t http://itsecgames.com/

![Screenshot 2023-11-07 at 15 31 42](https://github.com/gotr00t0day/Gsec/assets/34093136/7360b45c-3ecd-45c1-8875-55ce109c9ca6)

Nothing on results.txt.

What could be the issue?

Ricardo

**Comment by gotr00t0day** [comment]
> This issue is solved. Just copied the nuclei-templates to the home diretory.
> 
> But now it says scan finished, but no results, even to a knowingly bad web page - http://itsecgames.com/
> 
> The command I used:
> 
> python3 gsec.py -t http://itsecgames.com/
> 
> ![Screenshot 2023-11-07 at 15 31 42](https://user-images.githubusercontent.com/34093136/281056319-7360b45c-3ecd-45c1-8875-55ce109c9ca6.png)
> 
> Nothing on results.txt.
> 
> What could be the issue?
> 
> Ricardo

There's no issue, if it doesn't find anything it usually means nuclei or any of the other custom scripts didn't find any vulnerabilities.
