### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by sasholy** [gotr00t0day/Gsec#11]
hi
what's the problema?
`┌──(kali㉿kali)-[~/Gsec]
└─$ python3 gsec.py -t http://testphp.vulnweb.com/
Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 4, in <module>
    from utils import param_finder, javascript_scanner, headers
ImportError: cannot import name 'headers' from 'utils' (/home/kali/Gsec/utils/__init__.py)
`
thx

**Comment by gotr00t0day** [comment]
I forgot to add headers.py to the utils directory on the latest release. It should work now if you do a pull request.

**Comment by sasholy** [comment]
┌──(kali㉿kali)-[~/Gsec]
└─$ python3 gsec.py -t http://testphp.vulnweb.com/
Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 7, in <module>
    from vuln_db import hostheader_injection, nuclei_vulns, corsmisconfig, crossdomain, head_vuln, cache_poisoning, webservers_vulns, nmap_vuln, xss, broken_links
ImportError: cannot import name 'xss' from 'vuln_db' (/home/kali/Gsec/vuln_db/__init__.py)

**Comment by gotr00t0day** [comment]
Its fixed now.

**Comment by sasholy** [comment]
┌──(kali㉿kali)-[~/Gsec]
└─$ python3 gsec.py -t http://testphp.vulnweb.com/
Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 7, in <module>
    from vuln_db import hostheader_injection, nuclei_vulns, corsmisconfig, crossdomain, head_vuln, cache_poisoning, webservers_vulns, nmap_vuln, xss, broken_links
  File "/home/kali/Gsec/vuln_db/xss.py", line 3, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
