### ISSUE TITLE
 invalid escape sequence

### ISSUE THREAD

**Issue by sasholy** [gotr00t0day/Gsec#12]
hi

──(kali㉿kali)-[~/Gsec]
└─$ python3 gsec.py -t http://testphp.vulnweb.com/
/home/kali/Gsec/gsec.py:42: SyntaxWarning: invalid escape sequence '\ '
  """
/home/kali/Gsec/utils/wafscanner.py:42: SyntaxWarning: invalid escape sequence '\s'
  if waf_list in r.text or "Let\s Encrypt" in r.text:
Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 7, in <module>
    from vuln_db import hostheader_injection, nuclei_vulns, corsmisconfig, crossdomain, head_vuln, cache_poisoning, webservers_vulns, nmap_vuln, xss, broken_links
  File "/home/kali/Gsec/vuln_db/xss.py", line 3, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'

how fix it

**Comment by xalgord** [comment]
pip install fake_useragent

**Comment by sasholy** [comment]
> pip install fake_useragent

pip3 install

thx
