### ISSUE TITLE
Invalid Shodan API Key + /utils/subdomainscanners/certsh.sh : No such file or directory

### ISSUE THREAD

**Issue by darkanalytica1** [gotr00t0day/Gsec#4]
Got these two errors. 
I did input Shodan API Key correctly and even regenerated it, still shows as invalid when running the tool.
As for the certsh.sh there is no such file.

**Comment by darkanalytica1** [comment]
when I open subdomains.txt I get the error here: 
bash:  /home/kali/Gsec/utils/subdomainscanners/certsh.sh: No such file or directory

**Comment by gotr00t0day** [comment]
> when I open subdomains.txt I get the error here: bash: /home/kali/Gsec/utils/subdomainscanners/certsh.sh: No such file or directory

Nice catch, I forgot to push the utils/subdomainscanner to the repo, but you can now do a pull request and you're good to go.

**Comment by gotr00t0day** [comment]
> Got these two errors. I did input Shodan API Key correctly and even regenerated it, still shows as invalid when running the tool. As for the certsh.sh there is no such file.

Did you add the Shodan API key to .shodan in the core directory?

**Comment by darkanalytica1** [comment]
Yes, the file was hidden, but I found it and inserted several times valid api key, every time when running I got the same feedback "invalid api key"

**Comment by darkanalytica1** [comment]
> 

Great, will try again in the morning l, thank you

**Comment by darkanalytica1** [comment]
└─$ python3 gsec.py -t https://center-inform.ru --passive_recon
Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 3, in <module>
    from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon
  File "/home/kali/Gsec/utils/cmsscanner.py", line 4, in <module>
    from plugins import agent_list, versioncheck
ImportError: cannot import name 'versioncheck' from 'plugins' (/home/kali/Gsec/plugins/_init_.py)

**Comment by gotr00t0day** [comment]
I removed it in the latest release
