### ISSUE TITLE
Unable to run Normal/Active scan

### ISSUE THREAD

**Issue by Karan321** [gotr00t0day/Gsec#6]
Whenever trying to run "sudo python3 gsec.py -t https://domain.com i get an error as below:

Traceback (most recent call last):
  File "/home/kali/Gsec/gsec.py", line 3, in <module>
    from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon, path_traversal, crawler, osdetect
  File "/home/kali/Gsec/utils/techscanner.py", line 1, in <module>
    from builtwith import builtwith
ModuleNotFoundError: No module named 'builtwith'

**Comment by gotr00t0day** [comment]
> Whenever trying to run "sudo python3 gsec.py -t https://domain.com i get an error as below:
> 
> Traceback (most recent call last): File "/home/kali/Gsec/gsec.py", line 3, in from utils import portscanner, loginscanner, techscanner, cmsscanner, passive_recon, path_traversal, crawler, osdetect File "/home/kali/Gsec/utils/techscanner.py", line 1, in from builtwith import builtwith ModuleNotFoundError: No module named 'builtwith'

You need to "sudo pip3 install builtwith" or you can just "sudo pip3 install -r requirements.txt"

**Comment by Ravikm941** [comment]
try to run sudo python3 gsec.py -t https://domain.com i get this error as below.

Traceback (most recent call last):
  File "/home/rat/Desktop/Got-GSECTool/Gsec/gsec.py", line 4, in <module>
    from plugins import phpcheck, optionscheck, shellshock, robots, favicon, auth_tokens
  File "/home/rat/Desktop/Got-GSECTool/Gsec/plugins/favicon.py", line 4, in <module>
    import mmh3
ModuleNotFoundError: No module named 'mmh3'

**Comment by gotr00t0day** [comment]
> try to run sudo python3 gsec.py -t https://domain.com i get this error as below.
> 
> Traceback (most recent call last): File "/home/rat/Desktop/Got-GSECTool/Gsec/gsec.py", line 4, in from plugins import phpcheck, optionscheck, shellshock, robots, favicon, auth_tokens File "/home/rat/Desktop/Got-GSECTool/Gsec/plugins/favicon.py", line 4, in import mmh3 ModuleNotFoundError: No module named 'mmh3'

You might need to run pip as sudo and install requirements.txt

**Comment by gotr00t0day** [comment]
I changed a few things, Now you don't need to run gsec as root anymore and it won't give you an error, it will just skip the OS detection.
