### ISSUE TITLE
Invalid shodan api key

### ISSUE THREAD

**Issue by martino1988** [gotr00t0day/Gsec#9]
Hi,
i dont know why but i get an issue with my api key (see attached imagefile)

![image](https://github.com/gotr00t0day/Gsec/assets/61902639/a0af9093-116e-4a04-be35-225f173d56cf)

**Comment by gotr00t0day** [comment]
@martino1988 You need to ass your shodan api key to core/.shodan

**Comment by martino1988** [comment]
My shodan key is in the core/.shodan file

**Comment by gotr00t0day** [comment]
> My shodan key is in the core/.shodan file

You probably need to generate a new key.

**Comment by martino1988** [comment]
I did that already. Maybe its because i'm on an free plan? is there a difference in the api key?
My api key looks lke this: 0IaKsbTZx81WRcmqyoz2uW7Xe23pUaw7 (Of course this is not my api key, I changed it but the format is this.)

**Comment by gotr00t0day** [comment]
> I did that already. Maybe its because i'm on an free plan? is there a difference in the api key? My api key looks lke this: 0IaKsbTZx81WRcmqyoz2uW7Xe23pUaw7 (Of course this is not my api key, I changed it but the format is this.)

I'm not sure why it's not working for you, I've installed nuclei on my VM and it work just fine. I think the problem is on your end.

**Comment by sasholy** [comment]
hi
I open the folder core in terminal, then vim .shodan, insert my api :wq and - Invalid shodan api key
how do you insert the api?
thx
